#include "seed_length_calculator.h"

// This function takes a list of guides generated by CRISPR_shRNA_Map_Count.cpp and number of guides as input
// This function returns maximum and minimum guide lengths as output

int seed_length_calculator(std::string guide[], int number_of_guides){ 
// you cant pass an array to a function. Only the address of 1st element &guide[0] is being passed to the function
// So, you need to indicate the size of the array as separate parameter
	
	int max = 0;
	int min = 1000;
		
    for(int i=0;i<number_of_guides;++i){
		if (guide[i].length() > max){
			max = guide[i].length();
		}
	
		if (guide[i].length() < min){
			min=guide[i].length();
		}
	}
	
	//std::cout << "min: " << min << "\n";
	//std::cout << "number_of_guides: " << number_of_guides << "\n";
	
	int seed_length = min/3;
	
	if (seed_length < 8){
		seed_length = 8;
	}
	if (seed_length >20){
		seed_length =20;
	}
	
	return seed_length;
}