#!/bin/bash
#SBATCH --job-name=Biomodal_get
#SBATCH --mem=250G
#SBATCH --cpus-per-task=8
#SBATCH --output=%x_%j.log

#===============================================================================
# 📄 Script   : 06_biomodal_get.sh
# 📌 Purpose  : Run modality biological QC and extract regional methylation
#               statistics (mean, count, sum, fraction) for ALL samples.
#
#               Outputs per genomic region per sample:
#                 - biological_qc  : QC plots and metrics
#                 - get_mean       : mean total_c per region
#                 - get_count      : CpG count per region
#                 - get_sum        : sum of mc, hmc, total_c per region
#                 - get_regional_frac : mc and hmc fraction per region
#
# 🔁 Depends  : 05_biomodal_annotation.sh must have been run first
#               (annotation BED files must exist)
#
# 📝 Notes    :
#   - ALL samples are included regardless of coverage — even low coverage
#     samples contribute meaningful genome-wide fraction estimates when
#     averaging across millions of CpGs (law of large numbers). Sample
#     exclusion based on coverage is only relevant for per-CpG DMR calling
#     which is handled separately in 07_biomodal_dmr.sh
#
#   - Only CG (CpG) context ZARR files are used — CHG and CHH contexts are
#     skipped because non-CpG methylation is biologically negligible in human
#     somatic tissue (~0.1% as confirmed in QC: see merged_QC_summary.xlsx).
#     CHG/CHH are relevant in plants and during early embryogenesis but not
#     in the cancer/treatment context of this project.
#
#   - Sample sheet must have a column matching ORDER_COLUMN for grouping
#===============================================================================

#===============================================================================
# 🚀 Environment
#===============================================================================

source "/home/kailasamms/miniconda3/etc/profile.d/conda.sh"
conda activate omics
echo "✅ Environment activated: omics"

set -euo pipefail

#===============================================================================
# 🔎 Detect input files
#===============================================================================

HOME_DIR="/home/kailasamms"
DUET_DIR="${HOME_DIR%/}/analysis/Biomodal/Kevin_Carotuximab/01.duet"

# --- Detect CG ZARR files only ---
# CHG and CHH contexts are skipped — see script header notes above
echo "⚙️ Looking for CG ZARR files in ${DUET_DIR}"
shopt -s nullglob
ZARR_ARRAY=("${DUET_DIR%/}"/duet-*/sample_outputs/zarr_store/CG/*.CG.zarrz)
shopt -u nullglob
echo "Found ${#ZARR_ARRAY[@]} CG ZARR files"

# --- Check if files exist ---
if [ ${#ZARR_ARRAY[@]} -eq 0 ]; then
    echo "❌ No CG ZARR files found in ${DUET_DIR}. Aborting."
    exit 1
fi

# --- Print detected samples ---
echo "Samples detected:"
for z in "${ZARR_ARRAY[@]}"; do
    echo "  → $(basename "${z}")"
done

#===============================================================================
# ⚙️ Arguments
#===============================================================================

OUTPUT_DIR="${HOME_DIR%/}/analysis/Biomodal/Kevin_Carotuximab/03.modality"

# Annotation BED files — generated by 05_biomodal_annotation.sh
REF_DIR="${HOME_DIR%/}/resources/genomes"
BED_SUBGENE="${REF_DIR%/}/GRCh38_v115_biomodal_annotation_subgene.bed.gz"
BED_GENE="${REF_DIR%/}/GRCh38_v115_biomodal_annotation_gene.bed.gz"

# 💡 RESOLUTION SELECTION CRITERIA:
# We are intentionally using BED_GENE (~177k regions) for all regional metric 
# extractions and completely omitting genome-wide calculations on BED_SUBGENE. 
# Why?
# 1. Statistical Overkill: Subgene tracking yields 3.75+ million elements 
#    (mostly redundant exons/introns), creating an unreadable matrix.
# 2. Computational Stability: Scaling 3.75 million regions across 24 samples 
#    for pairwise metrics triggers severe Out-Of-Memory (OOM) cluster crashes 
#    during in-memory plotting steps.
# 3. Streamlined Downstream: BED_GENE comprehensively captures the active regulatory 
#    landscape (Promoters, Gene Bodies, CpG Islands, Shores, and Shelves) in a clean 
#    format that loads smoothly into R and Python.

# Sample sheet — must contain sample IDs and grouping column
PROJ_DIR="${HOME_DIR%/}/scripts/nextflow/projects/Biomodal/Kevin_Carotuximab"
SAMPLE_SHEET="${PROJ_DIR%/}/Kevin_Carotuximab_metadata.csv"

# Column in sample sheet used to aggregate/group samples for biological QC
ORDER_COLUMN="Group"

# Coverage and context filters
# min-coverage 0  : include all CpGs regardless of coverage depth
#                   (we want fractions from all samples including low coverage)
# num-contexts 0  : no minimum number of CpG contexts required per region
MIN_COVERAGE=0
NUM_CONTEXTS=0

#===============================================================================
# 📋 Job Info
#===============================================================================

echo "=========================================================="
printf "Start date      : %s\n" "$(date)"
printf "Job name        : %s\n" "${SLURM_JOB_NAME}"
printf "Job ID          : %s\n" "${SLURM_JOB_ID}"
printf "Cores           : %s\n" "${SLURM_CPUS_PER_TASK}"
echo "=========================================================="
printf "Base dir        : %s\n" "${HOME_DIR}"
printf "Output dir      : %s\n" "${OUTPUT_DIR}"
printf "BED subgene     : %s\n" "${BED_SUBGENE}"
printf "BED gene        : %s\n" "${BED_GENE}"
printf "Sample sheet    : %s\n" "${SAMPLE_SHEET}"
printf "Order column    : %s\n" "${ORDER_COLUMN}"
printf "ZARR files      : %s\n" "${#ZARR_ARRAY[@]}"
echo "=========================================================="

#===============================================================================
# 🔍 Pre-flight checks
#===============================================================================

[[ -f "${BED_SUBGENE}" ]] || { echo "❌ Subgene BED not found: ${BED_SUBGENE}. Run 05_biomodal_annotation.sh first."; exit 1; }
[[ -f "${BED_GENE}" ]]    || { echo "❌ Gene BED not found: ${BED_GENE}. Run 05_biomodal_annotation.sh first."; exit 1; }
[[ -f "${SAMPLE_SHEET}" ]] || { echo "❌ Sample sheet not found: ${SAMPLE_SHEET}"; exit 1; }

mkdir -p "${OUTPUT_DIR}"

#===============================================================================
# 🔬 Biological QC
#
# Generates QC plots and metrics across all samples grouped by ORDER_COLUMN.
# Useful for identifying outliers, batch effects, clustering by condition.
# Uses subgene BED for regional aggregation.
#===============================================================================

echo "=========================================================="
echo "🔬 Running biological QC..."
echo "=========================================================="

modality biological-qc \
    --zarr-path "${ZARR_ARRAY[@]}" \
    --sample-sheet "${SAMPLE_SHEET}" \
    --order-by-group "${ORDER_COLUMN}" \
    --output-dir "${OUTPUT_DIR%/}/biological_qc_sample"

modality biological-qc \
    --zarr-path "${ZARR_ARRAY[@]}" \
    --sample-sheet "${SAMPLE_SHEET}" \
    --aggregate-by-group "${ORDER_COLUMN}" \
    --output-dir "${OUTPUT_DIR%/}/biological_qc_group"

if [ $? -eq 0 ]; then
    echo "✅ Biological QC completed successfully."
else
    echo "❌ Biological QC failed."
    exit 1
fi

#===============================================================================
# 📊 Get Mean (total_c only)
#
# Mean total cytosine modification (mC + hmC) per genomic region per sample.
# Only total_c is computed here — mC and hmC fractions are computed separately
# via get regional-frac below which is the more informative metric.
# Includes --heatmap flag to generate visual overview across all samples.
#===============================================================================

echo "=========================================================="
echo "📊 Running get mean (total_c)..."
echo "=========================================================="

modality get mean \
    --zarr-path "${ZARR_ARRAY[@]}" \
    --fields total_c \
    --bedfile "${BED_GENE}" \
    --sample-sheet "${SAMPLE_SHEET}" \
    --min-coverage "${MIN_COVERAGE}" \
    --num-contexts "${NUM_CONTEXTS}" \
    --heatmap \
    --output-dir "${OUTPUT_DIR%/}/get_mean"

if [ $? -eq 0 ]; then
    echo "✅ Get mean completed successfully."
else
    echo "❌ Get mean failed."
    exit 1
fi

#===============================================================================
# 📊 Get Count (total_c only)
#
# Number of CpGs with coverage > min_coverage per genomic region per sample.
# Only total_c is needed — mc/hmc/total_c counts are identical (same CpG sites)
# so computing all three would be redundant.
# Useful for understanding which regions have sufficient coverage per sample.
#===============================================================================

echo "=========================================================="
echo "📊 Running get count (total_c)..."
echo "=========================================================="

modality get count \
    --zarr-path "${ZARR_ARRAY[@]}" \
    --fields total_c \
    --bedfile "${BED_GENE}" \
    --sample-sheet "${SAMPLE_SHEET}" \
    --min-coverage "${MIN_COVERAGE}" \
    --num-contexts "${NUM_CONTEXTS}" \
    --output-dir "${OUTPUT_DIR%/}/get_count"

if [ $? -eq 0 ]; then
    echo "✅ Get count completed successfully."
else
    echo "❌ Get count failed."
    exit 1
fi

#===============================================================================
# 📊 Get Sum (mc, hmc, total_c)
#
# Sum of methylation signal per genomic region per sample.
# All three fields are computed here because mc and hmc have distinct
# biological meaning — sum is the raw signal before normalisation and is
# needed to compute custom fractions downstream if required.
#===============================================================================

echo "=========================================================="
echo "📊 Running get sum (mc, hmc, total_c)..."
echo "=========================================================="

modality get sum \
    --zarr-path "${ZARR_ARRAY[@]}" \
    --fields mc hmc total_c \
    --bedfile "${BED_GENE}" \
    --sample-sheet "${SAMPLE_SHEET}" \
    --min-coverage "${MIN_COVERAGE}" \
    --num-contexts "${NUM_CONTEXTS}" \
    --output-dir "${OUTPUT_DIR%/}/get_sum"

if [ $? -eq 0 ]; then
    echo "✅ Get sum completed successfully."
else
    echo "❌ Get sum failed."
    exit 1
fi

#===============================================================================
# 📊 Get Regional Fraction (mc, hmc)
#
# Fraction of mC and hmC over total_c per genomic region per sample.
# This is the PRIMARY output for trend analysis and biological interpretation:
#   - mc fraction  = proportion of methylcytosine at CpGs in each region
#   - hmc fraction = proportion of hydroxymethylcytosine at CpGs in each region
# Includes --heatmap flag for visual overview.
# total_c fraction is not computed — by definition it equals 1.0 everywhere.
# Run twice: once with subgene BED, once with gene BED for different resolution.
#===============================================================================

echo "=========================================================="
echo "📊 Running get regional-frac (mc, hmc) — gene resolution..."
echo "=========================================================="

modality get regional-frac \
    --zarr-path "${ZARR_ARRAY[@]}" \
    --fields mc hmc \
    --bedfile "${BED_GENE}" \
    --sample-sheet "${SAMPLE_SHEET}" \
    --min-coverage "${MIN_COVERAGE}" \
    --num-contexts "${NUM_CONTEXTS}" \
    --heatmap \
    --output-dir "${OUTPUT_DIR%/}/get_regional_frac"

if [ $? -eq 0 ]; then
    echo "✅ Get regional-frac (gene) completed successfully."
else
    echo "❌ Get regional-frac (gene) failed."
    exit 1
fi

#===============================================================================
# 📦 Extract compressed outputs to flat TSV files
#
# modality outputs are gzipped TSV files nested in subdirectories.
# These are concatenated into single flat TSV files for easier downstream
# use in R/Python analysis scripts.
#===============================================================================

echo "=========================================================="
echo "📦 Extracting compressed TSV outputs..."
echo "=========================================================="

zcat "${OUTPUT_DIR}/get_mean/"*/Extract_total_c_mean_*.tsv.gz \
    > "${OUTPUT_DIR}/get_mean/mean_total_c.tsv"
echo "✅ mean_total_c.tsv"

zcat "${OUTPUT_DIR}/get_count/"*/Extract_total_c_count_*.tsv.gz \
    > "${OUTPUT_DIR}/get_count/count_total_c.tsv"
echo "✅ count_total_c.tsv"

zcat "${OUTPUT_DIR}/get_sum/"*/Extract_mc_sum_*.tsv.gz \
    > "${OUTPUT_DIR}/get_sum/sum_mc.tsv"
zcat "${OUTPUT_DIR}/get_sum/"*/Extract_hmc_sum_*.tsv.gz \
    > "${OUTPUT_DIR}/get_sum/sum_hmc.tsv"
zcat "${OUTPUT_DIR}/get_sum/"*/Extract_total_c_sum_*.tsv.gz \
    > "${OUTPUT_DIR}/get_sum/sum_total_c.tsv"
echo "✅ sum_mc.tsv, sum_hmc.tsv, sum_total_c.tsv"

zcat "${OUTPUT_DIR}/get_regional_frac/"*/Extract_mc_regional-frac_*.tsv.gz \
    > "${OUTPUT_DIR}/get_regional_frac/frac_mc.tsv"
zcat "${OUTPUT_DIR}/get_regional_frac/"*/Extract_hmc_regional-frac_*.tsv.gz \
    > "${OUTPUT_DIR}/get_regional_frac/frac_hmc.tsv"
echo "✅ frac_mc.tsv, frac_hmc.tsv"

#===============================================================================
# 📋 Summary
#===============================================================================

echo ""
echo "=========================================================="
printf "End date        : %s\n" "$(date)"
echo "=========================================================="
echo "✅ All modality get steps completed successfully."
echo ""
echo "📁 Outputs saved to: ${OUTPUT_DIR}"
echo "   biological_qc/"
echo "   get_mean/mean_total_c.tsv"
echo "   get_count/count_total_c.tsv"

echo "   get_sum/sum_mc.tsv"
echo "   get_sum/sum_hmc.tsv"
echo "   get_sum/sum_total_c.tsv"

echo "   get_regional_frac/frac_mc.tsv"
echo "   get_regional_frac/frac_hmc.tsv"
echo "=========================================================="
